language: android

sudo: required

env:
  global:
    - BUILD_TOOLS=25.0.2

matrix:
  include:
    - env:
      - DESC="Basic PR verification"
      - CMD="./.ci/travis/check_pr.sh;./.ci/validate-codecov.sh"
      - CMD_AFTER_SUCCESS='echo "PR validation successful"'
      - CMD_AFTER_FAILURE='echo "PR validation failed"'

    - env:
      - DESC="API 21"
      - EMULATOR_API=21
      - IMAGE=sys-img-armeabi-v7a-android-$EMULATOR_API
      - CMD="./gradlew clean build coverage;killall adb"
      - CMD_BEFORE=".ci/travis/startEmulator.sh"
      - CMD_AFTER_SUCCESS="bash <(curl -s https://codecov.io/bash);.ci/travis/apkHost.sh"
      - CMD_AFTER_FAILURE=".ci/travis/pastebinit.sh"

    - env:
      - DESC="API 22"
      - EMULATOR_API=22
      - IMAGE=sys-img-armeabi-v7a-android-$EMULATOR_API
      - CMD="./gradlew clean build coverage;killall adb"
      - CMD_BEFORE=".ci/travis/startEmulator.sh"
      - CMD_AFTER_SUCCESS="bash <(curl -s https://codecov.io/bash);.ci/travis/apkHost.sh"
      - CMD_AFTER_FAILURE=".ci/travis/pastebinit.sh"

android:
  components:
    - tools
    - tools
    - platform-tools

    - build-tools-${BUILD_TOOLS}

    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-$EMULATOR_API
    - extra-android-m2repository
    - extra-android-support
    #- extra-google-android-support

    - android-$EMULATOR_API

    - $IMAGE

jdk:
  - oraclejdk8

os:
  - linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - ~/.m2

addons:
  apt:
    packages:
      - pastebinit
      - jq

licenses:
  - '.+'

before_install:
  - android list targets
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

# Emulator Management: Create, Start and Wait
before_script:
  - |
      set -e
           eval $CMD_BEFORE;

script:
  - |
      set -e
           eval $CMD;

after_failure:
  - |
       set -e
           eval $CMD_AFTER_FAILURE;

after_success:
  - |
       set -e
           eval $CMD_AFTER_SUCCESS;

notifications:
  slack: macbitsgoa:ll3YNWLieRUgdN3RNSwkOoeW

#If you don’t want to run a build for a particular commit for any reason,
# add [ci skip] or [skip ci] to the git commit message.
#Commits that have [ci skip] or [skip ci] anywhere in the commit messages
#are ignored by Travis CI.
